# Generated by Django 5.2.17 on 2026-09-21 13:45

import core.i18n
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "store_name_ar",
                    models.CharField(
                        default="رونق للإكسسوارات",
                        max_length=120,
                        verbose_name="store name (Arabic)",
                    ),
                ),
                (
                    "store_name_en",
                    models.CharField(
                        default="Rawnaq Accessories",
                        max_length=120,
                        verbose_name="store name (English)",
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        default="972553003327",
                        help_text="Digits only with country code, used for wa.me links. Example: 972553003327",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_international_phone",
                                message="Use digits only, including the country code, without + or spaces (for example 972553003327).",
                                regex="^[1-9][0-9]{7,14}$",
                            )
                        ],
                        verbose_name="WhatsApp number (international)",
                    ),
                ),
                (
                    "whatsapp_display_number",
                    models.CharField(
                        default="0553003327",
                        max_length=20,
                        verbose_name="WhatsApp number (as displayed)",
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        default="https://www.instagram.com/rawnaq_accessories1/",
                        verbose_name="Instagram URL",
                    ),
                ),
                (
                    "default_delivery_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="default delivery fee",
                    ),
                ),
                (
                    "free_delivery_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Orders at or above this amount (after discounts) get free delivery. Leave empty to disable.",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="free-delivery threshold",
                    ),
                ),
                (
                    "delivery_notice_ar",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="delivery notice (Arabic)",
                    ),
                ),
                (
                    "delivery_notice_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="delivery notice (English)",
                    ),
                ),
                (
                    "sale_banner_text_ar",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="sale banner text (Arabic)",
                    ),
                ),
                (
                    "sale_banner_text_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="sale banner text (English)",
                    ),
                ),
                (
                    "sale_banner_enabled",
                    models.BooleanField(default=False, verbose_name="show sale banner"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "site settings",
                "verbose_name_plural": "site settings",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("pk", 1)), name="site_settings_singleton"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("default_delivery_fee__gte", 0)),
                        name="site_settings_fee_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("free_delivery_threshold__isnull", True),
                            ("free_delivery_threshold__gte", 0),
                            _connector="OR",
                        ),
                        name="site_settings_threshold_non_negative",
                    ),
                ],
            },
            bases=(core.i18n.LocalizedFieldsMixin, models.Model),
        ),
    ]
