# Generated by Django 5.2.17 on 2026-09-21 13:45

import accounts.models
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="full name"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_phone",
                                message="Enter a valid phone number, for example 0501234567.",
                                regex="^\\+?[0-9][0-9 \\-]{7,18}[0-9]$",
                            )
                        ],
                        verbose_name="phone number",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Staff members can access the owner dashboard.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="For example: Home, Work",
                        max_length=60,
                        verbose_name="label",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="city / town")),
                ("street", models.CharField(max_length=150, verbose_name="street")),
                (
                    "building_number",
                    models.CharField(
                        max_length=20, verbose_name="building / house number"
                    ),
                ),
                (
                    "apartment",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="apartment"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=12, verbose_name="postal code"
                    ),
                ),
                (
                    "landmark",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="landmark or delivery notes",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="default address"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "address",
                "verbose_name_plural": "addresses",
                "ordering": ["-is_default", "-updated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="accounts_user_email_ci_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["user", "-updated_at"], name="accounts_address_user_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("user",),
                name="accounts_one_default_address_per_user",
            ),
        ),
    ]
