"""SKUs are generated by the server, unique, and stable for the life of a row."""

import pytest
from django.db import IntegrityError, connection

from catalog.models import Product, ProductVariant
from catalog.skus import PRODUCT_SKU_PREFIX, VARIANT_SKU_PREFIX, generate_product_sku, generate_variant_sku
from conftest import make_brand, make_product

pytestmark = pytest.mark.django_db


def test_generators_use_distinct_prefixes_and_random_content():
    product_skus = {generate_product_sku() for _ in range(200)}
    variant_skus = {generate_variant_sku() for _ in range(200)}
    assert len(product_skus) == 200 and len(variant_skus) == 200
    assert all(sku.startswith(PRODUCT_SKU_PREFIX) for sku in product_skus)
    assert all(sku.startswith(VARIANT_SKU_PREFIX) for sku in variant_skus)
    assert not product_skus & variant_skus
    # Long enough that concurrent requests never need coordination.
    assert all(len(sku) - len(PRODUCT_SKU_PREFIX) >= 12 for sku in product_skus)


def test_products_and_variants_get_a_sku_without_being_given_one():
    product = make_product(variants=2)
    assert product.sku.startswith(PRODUCT_SKU_PREFIX)
    variants = list(product.variants.all())
    assert len(variants) == 2
    for variant in variants:
        assert variant.sku.startswith(VARIANT_SKU_PREFIX)
    assert len({variant.sku for variant in variants}) == 2


def test_generated_skus_are_non_empty_and_unique_across_rows():
    products = [make_product(variants=2) for _ in range(5)]
    skus = [product.sku for product in products] + [v.sku for p in products for v in p.variants.all()]
    assert all(skus)
    assert len(set(skus)) == len(skus)


def test_editing_a_product_or_variant_never_changes_its_sku():
    brand = make_brand()
    product = make_product(brand, variants=1)
    variant = product.variants.get()
    original_product_sku, original_variant_sku = product.sku, variant.sku

    product.name_en = "A completely different name"
    product.name_ar = "اسم مختلف تمامًا"
    product.slug = "a-completely-different-slug"
    product.brand = make_brand()
    product.save()
    variant.name_en = "Rose gold"
    variant.name_ar = "ذهبي وردي"
    variant.color_hex = "#C9A85C"
    variant.save()

    product.refresh_from_db()
    variant.refresh_from_db()
    assert product.sku == original_product_sku
    assert variant.sku == original_variant_sku


def test_a_blank_sku_is_filled_in_by_the_model():
    """Defence in depth for rows built outside the normal creation path."""
    product = make_product()
    Product.objects.filter(pk=product.pk).update(sku="")
    product.refresh_from_db()
    product.save()
    product.refresh_from_db()
    assert product.sku.startswith(PRODUCT_SKU_PREFIX)


def test_sku_uniqueness_is_still_enforced_by_the_database():
    first = make_product()
    second = make_product()
    with connection.cursor() as cursor, pytest.raises(IntegrityError):
        cursor.execute("UPDATE catalog_product SET sku = %s WHERE id = %s", [first.sku, second.pk])


def test_manually_assigned_skus_survive(site_settings):
    """Codes assigned before SKUs became automatic are left exactly as they are."""
    product = make_product()
    variant = product.variants.first()
    Product.objects.filter(pk=product.pk).update(sku="NDO-001")
    ProductVariant.objects.filter(pk=variant.pk).update(sku="NDO-001-A")

    product.refresh_from_db()
    variant.refresh_from_db()
    assert (product.sku, variant.sku) == ("NDO-001", "NDO-001-A")

    # Re-saving an existing row keeps the legacy code rather than replacing it.
    product.name_en = "Renamed"
    product.save()
    variant.stock_quantity = 42
    variant.save()
    product.refresh_from_db()
    variant.refresh_from_db()
    assert (product.sku, variant.sku) == ("NDO-001", "NDO-001-A")


def test_sku_fields_are_not_editable_so_no_form_can_expose_them():
    assert Product._meta.get_field("sku").editable is False
    assert ProductVariant._meta.get_field("sku").editable is False
