# Generated by Django 5.2.17 on 2026-09-21 13:45

import core.i18n
import core.images
import core.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import re
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=120, verbose_name="name (Arabic)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=120, verbose_name="name (English)"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=140, unique=True, verbose_name="slug"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        upload_to=core.images.UploadTo("brands/logos"),
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            ),
                            core.validators.ImageUploadValidator(),
                        ],
                        verbose_name="logo / image",
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True,
                        upload_to=core.images.UploadTo("brands/banners"),
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            ),
                            core.validators.ImageUploadValidator(),
                        ],
                        verbose_name="banner image",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#F8C8DC",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_hex_color",
                                message="Enter a colour as a six-digit hexadecimal value, for example #F8C8DC.",
                                regex=re.compile("^#[0-9A-Fa-f]{6}$"),
                            )
                        ],
                        verbose_name="primary colour",
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#9E526F",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_hex_color",
                                message="Enter a colour as a six-digit hexadecimal value, for example #F8C8DC.",
                                regex=re.compile("^#[0-9A-Fa-f]{6}$"),
                            )
                        ],
                        verbose_name="secondary colour",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "brand",
                "verbose_name_plural": "brands",
                "ordering": ["display_order", "name_en"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"],
                        name="catalog_brand_active_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("primary_color__regex", "^#[0-9A-Fa-f]{6}$")
                        ),
                        name="brand_primary_color_hex",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("secondary_color__regex", "^#[0-9A-Fa-f]{6}$")
                        ),
                        name="brand_secondary_color_hex",
                    ),
                ],
            },
            bases=(core.i18n.LocalizedFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=120, verbose_name="name (Arabic)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=120, verbose_name="name (English)"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=140, unique=True, verbose_name="slug"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to=core.images.UploadTo("categories"),
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            ),
                            core.validators.ImageUploadValidator(),
                        ],
                        verbose_name="image",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ["display_order", "name_en"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"],
                        name="catalog_category_active_idx",
                    )
                ],
            },
            bases=(core.i18n.LocalizedFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=200, verbose_name="name (Arabic)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=200, verbose_name="name (English)"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=220, unique=True, verbose_name="slug"),
                ),
                (
                    "description_ar",
                    models.TextField(blank=True, verbose_name="description (Arabic)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="description (English)"),
                ),
                (
                    "sku",
                    models.CharField(max_length=64, unique=True, verbose_name="SKU"),
                ),
                (
                    "regular_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="regular price (₪)",
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("CONFIRMED", "Confirmed by brand"),
                            ("NOT_CONFIRMED", "Not confirmed by brand"),
                            ("UNKNOWN", "Status unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                        verbose_name="brand verification",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="featured"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.brand",
                        verbose_name="brand",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="categories",
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "ordering": ["-created_at"],
            },
            bases=(core.i18n.LocalizedFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=core.images.UploadTo("products"),
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            ),
                            core.validators.ImageUploadValidator(),
                        ],
                        verbose_name="image",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        upload_to=core.images.UploadTo("products/thumbs"),
                        verbose_name="thumbnail",
                    ),
                ),
                (
                    "alt_text_ar",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="alt text (Arabic)"
                    ),
                ),
                (
                    "alt_text_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="alt text (English)"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="primary image"),
                ),
                (
                    "width",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "height",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "product image",
                "verbose_name_plural": "product images",
                "ordering": ["-is_primary", "display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "name_ar",
                    models.CharField(
                        max_length=120, verbose_name="variant name (Arabic)"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=120, verbose_name="variant name (English)"
                    ),
                ),
                (
                    "color_name_ar",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="colour name (Arabic)"
                    ),
                ),
                (
                    "color_name_en",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="colour name (English)"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        blank=True,
                        help_text="#RRGGBB, optional",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_hex_color",
                                message="Enter a colour as a six-digit hexadecimal value, for example #F8C8DC.",
                                regex=re.compile("^#[0-9A-Fa-f]{6}$"),
                            )
                        ],
                        verbose_name="colour swatch",
                    ),
                ),
                (
                    "sku",
                    models.CharField(max_length=64, unique=True, verbose_name="SKU"),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="stock quantity"
                    ),
                ),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave empty to use the product's regular price.",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="price override (₪)",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "product variant",
                "verbose_name_plural": "product variants",
                "ordering": ["display_order", "id"],
            },
            bases=(core.i18n.LocalizedFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=150, verbose_name="name (Arabic)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=150, verbose_name="name (English)"),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Percentage"),
                            ("FIXED", "Fixed amount (₪)"),
                        ],
                        max_length=12,
                        verbose_name="discount type",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage (1-100) or a fixed amount in shekels.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="value",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("STORE", "Entire store"),
                            ("BRAND", "Brand"),
                            ("CATEGORY", "Category"),
                            ("PRODUCT", "Individual product"),
                        ],
                        max_length=10,
                        verbose_name="applies to",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="starts at"
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave empty for no end date.",
                        null=True,
                        verbose_name="ends at",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="enabled"),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Higher priority wins when several promotions match an item. With equal priority, the biggest discount is applied.",
                        verbose_name="priority",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="catalog.brand",
                        verbose_name="brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="catalog.category",
                        verbose_name="category",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="catalog.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "promotion",
                "verbose_name_plural": "promotions",
                "ordering": ["-priority", "-starts_at"],
            },
            bases=(core.i18n.LocalizedFieldsMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["brand", "is_active"], name="catalog_product_brand_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "-created_at"], name="catalog_product_new_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_featured", "is_active"], name="catalog_product_featured_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["verification_status"], name="catalog_product_verif_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("regular_price__gt", 0)),
                name="product_regular_price_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("product",),
                name="catalog_one_primary_image_per_product",
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["product", "is_active"], name="catalog_variant_product_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["stock_quantity"], name="catalog_variant_stock_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock_quantity__gte", 0)),
                name="variant_stock_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("price_override__isnull", True),
                    ("price_override__gt", 0),
                    _connector="OR",
                ),
                name="variant_price_override_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("color_hex", ""),
                    ("color_hex__regex", "^#[0-9A-Fa-f]{6}$"),
                    _connector="OR",
                ),
                name="variant_color_hex_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="promotion",
            index=models.Index(
                fields=["is_enabled", "starts_at", "ends_at"],
                name="catalog_promo_active_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.CheckConstraint(
                condition=models.Q(("value__gt", 0)), name="promotion_value_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discount_type", "FIXED"),
                    models.Q(("discount_type", "PERCENTAGE"), ("value__lte", 100)),
                    _connector="OR",
                ),
                name="promotion_percentage_max_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ends_at__isnull", True),
                    ("ends_at__gt", models.F("starts_at")),
                    _connector="OR",
                ),
                name="promotion_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("brand__isnull", True),
                        ("category__isnull", True),
                        ("product__isnull", True),
                        ("scope", "STORE"),
                    ),
                    models.Q(
                        ("brand__isnull", False),
                        ("category__isnull", True),
                        ("product__isnull", True),
                        ("scope", "BRAND"),
                    ),
                    models.Q(
                        ("brand__isnull", True),
                        ("category__isnull", False),
                        ("product__isnull", True),
                        ("scope", "CATEGORY"),
                    ),
                    models.Q(
                        ("brand__isnull", True),
                        ("category__isnull", True),
                        ("product__isnull", False),
                        ("scope", "PRODUCT"),
                    ),
                    _connector="OR",
                ),
                name="promotion_scope_target_consistent",
            ),
        ),
    ]
