# Generated by Django 5.2.17 on 2026-09-21 13:45

import core.i18n
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        editable=False,
                        max_length=24,
                        unique=True,
                        verbose_name="order number",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=150, verbose_name="customer name"),
                ),
                (
                    "customer_email",
                    models.EmailField(max_length=254, verbose_name="customer email"),
                ),
                (
                    "customer_phone",
                    models.CharField(max_length=20, verbose_name="customer phone"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="city / town")),
                ("street", models.CharField(max_length=150, verbose_name="street")),
                (
                    "building_number",
                    models.CharField(
                        max_length=20, verbose_name="building / house number"
                    ),
                ),
                (
                    "apartment",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="apartment"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=12, verbose_name="postal code"
                    ),
                ),
                (
                    "landmark",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="landmark or delivery notes",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="longitude",
                    ),
                ),
                (
                    "location_accuracy_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=9,
                        null=True,
                        verbose_name="location accuracy (m)",
                    ),
                ),
                (
                    "location_consent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="location consent given at"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="subtotal"
                    ),
                ),
                (
                    "discount_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="discount total"
                    ),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="delivery fee"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="total"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RECEIVED", "Received"),
                            ("CONFIRMED", "Confirmed"),
                            ("PREPARING", "Preparing"),
                            ("OUT_FOR_DELIVERY", "Out for delivery"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "customer_notes",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="customer notes"
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="internal notes"),
                ),
                (
                    "language",
                    models.CharField(
                        default="ar", max_length=5, verbose_name="language"
                    ),
                ),
                (
                    "whatsapp_opened_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="WhatsApp opened at"
                    ),
                ),
                (
                    "stock_deducted_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="stock deducted at",
                    ),
                ),
                (
                    "stock_restored_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="stock restored at",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name_ar",
                    models.CharField(
                        max_length=200, verbose_name="product name (Arabic)"
                    ),
                ),
                (
                    "product_name_en",
                    models.CharField(
                        max_length=200, verbose_name="product name (English)"
                    ),
                ),
                (
                    "variant_name_ar",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="variant (Arabic)"
                    ),
                ),
                (
                    "variant_name_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="variant (English)"
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(blank=True, max_length=120, verbose_name="brand"),
                ),
                (
                    "promotion_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="promotion"
                    ),
                ),
                ("sku", models.CharField(max_length=64, verbose_name="SKU")),
                ("quantity", models.PositiveIntegerField(verbose_name="quantity")),
                (
                    "original_unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="original unit price",
                    ),
                ),
                (
                    "unit_discount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="discount per unit",
                    ),
                ),
                (
                    "final_unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="final unit price"
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="line total"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.promotion",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="catalog.productvariant",
                        verbose_name="variant",
                    ),
                ),
            ],
            options={
                "verbose_name": "order item",
                "verbose_name_plural": "order items",
                "ordering": ["id"],
            },
            bases=(core.i18n.LocalizedFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDING", "Pending"),
                            ("RECEIVED", "Received"),
                            ("CONFIRMED", "Confirmed"),
                            ("PREPARING", "Preparing"),
                            ("OUT_FOR_DELIVERY", "Out for delivery"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=20,
                        verbose_name="from",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RECEIVED", "Received"),
                            ("CONFIRMED", "Confirmed"),
                            ("PREPARING", "Preparing"),
                            ("OUT_FOR_DELIVERY", "Out for delivery"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=20,
                        verbose_name="to",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="note"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="changed at"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="changed by",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
            ],
            options={
                "verbose_name": "status change",
                "verbose_name_plural": "status history",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "-created_at"], name="orders_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer", "-created_at"], name="orders_customer_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["-created_at"], name="orders_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("delivery_fee__gte", 0),
                    ("discount_total__gte", 0),
                    ("subtotal__gte", 0),
                    ("total__gte", 0),
                ),
                name="order_amounts_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_total__lte", models.F("subtotal"))),
                name="order_discount_lte_subtotal",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "total",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("subtotal"), "-", models.F("discount_total")
                            ),
                            "+",
                            models.F("delivery_fee"),
                        ),
                    )
                ),
                name="order_total_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("latitude__isnull", True),
                        ("location_consent_at__isnull", True),
                        ("longitude__isnull", True),
                    ),
                    models.Q(
                        ("latitude__isnull", False),
                        ("location_consent_at__isnull", False),
                        ("longitude__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="order_location_requires_consent",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("latitude__isnull", True),
                    models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                    _connector="OR",
                ),
                name="order_latitude_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("longitude__isnull", True),
                    models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                    _connector="OR",
                ),
                name="order_longitude_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("stock_restored_at__isnull", True),
                    ("stock_deducted_at__isnull", False),
                    _connector="OR",
                ),
                name="order_restore_requires_deduction",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="order_item_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("final_unit_price__gte", 0),
                    ("original_unit_price__gte", 0),
                    ("unit_discount__gte", 0),
                ),
                name="order_item_prices_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "final_unit_price",
                        django.db.models.expressions.CombinedExpression(
                            models.F("original_unit_price"),
                            "-",
                            models.F("unit_discount"),
                        ),
                    )
                ),
                name="order_item_final_price_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "line_total",
                        django.db.models.expressions.CombinedExpression(
                            models.F("final_unit_price"), "*", models.F("quantity")
                        ),
                    )
                ),
                name="order_item_line_total_consistent",
            ),
        ),
        migrations.AddIndex(
            model_name="orderstatushistory",
            index=models.Index(
                fields=["order", "created_at"], name="orders_history_order_idx"
            ),
        ),
    ]
